### ISSUE TITLE
Basic examples do not work

### ISSUE THREAD

**Issue by mt-inside** [kapicorp/kadet#14]
python==3.8.5
kadet==0.1.2

I've made a copy of the two first, most basic examples from README.md. None of the serialisation looks like it should - it's full of type annotations, YAML refs, etc. This is sadly not usable for my purposes.

Code shown below with output mixed in.

```python
  from kadet import BaseObj
  from pprint import pprint
  import yaml
  
  ships = BaseObj()
  ships.root.type.container = ["panamax", "suezmax", "post-panamax"]                                       
  ships.root.type.carrier = ["conventional", "geared", "gearless"]                                         
  
  pprint(ships)
```
```python
<BaseObj at 0x7f804cf4f7c0 {'type': {'container': ['panamax', 'suezmax', 'post-panamax'], 'carrier': ['conventional', 'geared', 'gearless']}}>
```

```python
  print(yaml.dump(ships.dump()))
```
```yaml
!!python/object/apply:kadet.Dict
args:
- &id001 !!python/name:kadet.Dict ''
dictitems:
  type: !!python/object/apply:kadet.Dict
    args:
    - *id001
    dictitems:
      carrier:
      - conventional
      - geared
      - gearless
      container:
      - panamax
      - suezmax
      - post-panamax
```

```python
  class MyApp(BaseObj):
    def body(self):
      self.root.name = "myapp"
      self.root.inner.foo = "bar"
      self.root.list = [1, 2, 3]
  
  print(yaml.dump(MyApp().dump()))
```
```yaml
!!python/object/apply:kadet.Dict
args:
- &id001 !!python/name:kadet.Dict ''
dictitems:
  inner: !!python/object/apply:kadet.Dict
    args:
    - *id001
    dictitems:
      foo: bar
  list:
  - 1
  - 2
  - 3
  name: myapp
```
